### ISSUE TITLE
Usage with roles?

### ISSUE THREAD

**Issue by rndmh3ro** [teramako/playbook2uml#2]
Thanks for this great project, I really like it!

Is it possible to extend its functionality so it can also create UML diagrams for the tasks in roles?

**Comment by jeanlouisferey** [comment]
Thanks too, good job !

Not sure to answer to your question @rndmh3ro but, I tested it on one of my [role](https://github.com/jeanlouisferey/aws-securitygroup-grapher). I wrote as test a simple [playbook](https://github.com/jeanlouisferey/aws-securitygroup-grapher#example-playbook) and tried playbook2uml on it, and I got the image below which shows how my role works:
![image](https://user-images.githubusercontent.com/7669102/211806433-83ec93e3-7ec0-4dc1-a159-4656d5d73774.png)

**Comment by rndmh3ro** [comment]
Thanks for replying.

I noticed what my problem is. I use `include_role`.

Code:

```
- name: ansible-os-hardening
  hosts: all
  collections:
    - devsec.hardening
  tasks:
    - include_role:
        name: os_hardening
```

resulting UML:

```
@startuml
state "= Play: ansible-os-hardening" as play_1 {
    play_1 : | gather_facts | None |
    play_1 : | hosts | all |
    play_1 : | serial | [] |
    play_1 : | strategy | linear |
    state "== workaround for https://github.com/ansible/ansible/issues/66304" as task_1
    task_1 : Action **set_fact**
    task_1 : | ansible_virtualization_type | docker |
    task_1 : ....
    task_1 : **become** yes
    state "== include_role : os_hardening" as task_2
    task_2 : Action **include_role**
    task_2 : | name | os_hardening |
    task_2 : ....
    task_2 : **become** yes
}
[*] --> task_1
task_1 --> task_2
task_2 --> [*]
@enduml
```

It's logical that only the task `include_role` and not the contents of the role are shown. 

Maybe another feature request: There could be an option that the role included by `include_role` should be displayed too?

**Comment by teramako** [comment]
Thank you for your contribution to Issue.
I will write code to add the `--role` option this weekend.

> Maybe another feature request: There could be an option that the role included by include_role should be displayed too?

Could you use `import_role` loads a role statically instead of `include_role`.

**Comment by rndmh3ro** [comment]
> Could you use import_role loads a role statically instead of include_role.

Thanks, that works! Then I get all the tasks in the roles. Awesome!

**Comment by teramako** [comment]
I added `-R` or `--role` option.
Could you checkout `2-usage-with-roles` branch and test ?

An example is following:

```console
zsh 📁 playbook2uml on  2-usage-with-roles via 🐍 v3.8.12 (ansible)
❯ fd . test/roles/test_1
test/roles/test_1/tasks/
test/roles/test_1/tasks/main.yml
zsh 📁 playbook2uml on  2-usage-with-roles via 🐍 v3.8.12 (ansible)
❯ python -m playbook2uml.cli --title "test_1 role flow" --theme blueprint -R test_1 test
@startuml
title test_1 role flow
!theme blueprint
state "== test_1 : Say Hello" as task_1
task_1 : Action **debug**
task_1 : | msg | Hello `test_1' role |
state "== test_1 : Say 💩" as task_2
task_2 : Action **debug**
task_2 : | msg | 💩 |
[*] --> task_1
task_1 --> task_2
task_2 --> [*]
@enduml
```
![image](https://user-images.githubusercontent.com/32928/212346468-66d0efca-3101-4c10-b25a-0675453e8063.png)

**Comment by rndmh3ro** [comment]
This works great, thank you for your fast implementation!

**Comment by teramako** [comment]
Thank you for testing 😃
merged to main branch.
