### ISSUE TITLE
index out of range error

### ISSUE THREAD

**Issue by getvasanth** [teramako/playbook2uml#6]
I am trying to use this playbook2uml, but looks like for sum reason it fails

playbook2uml               0.2.1  

[uml@dev builder]$ cat playbooks/build_keycloak.yaml 
---
- name: "Building Keycloak package"
  hosts: localhost
  vars:
    keycloak_package_url: "{{ lookup('ini', 'repo-url', section='keycloak-package', file='envrc') }}"
  collections:
    - apps.build
  roles:
    - keycloak
[uml@dev builder]$ playbook2uml -T playbook  -R playbooks/build_keycloak.yaml 
[WARNING]: Ignoring invalid path provided to plugin path: '/home/umlbuilder/playbooks/build_keycloak.yaml' is not a directory
@startuml
title playbook
Traceback (most recent call last):
  File "/home/uml/.local/bin/playbook2uml", line 11, in <module>
    load_entry_point('playbook2uml', 'console_scripts', 'playbook2uml')()
  File "/home/uml/playbook2uml-main/playbook2uml/cli.py", line 52, in main
    for line in umlplaybook.generate():
  File "/home/uml/playbook2uml-main/playbook2uml/umlstate.py", line 462, in generate
    yield from current_state.generateRelation(next_state)
  File "/home/uml/playbook2uml-main/playbook2uml/umlstate.py", line 312, in generateRelation
    yield '[*] --> %s' % next.get_entry_point_name()
  File "/home/uml/playbook2uml-main/playbook2uml/umlstate.py", line 390, in get_entry_point_name
    return self.get_all_tasks()[0].get_entry_point_name()
  File "/home/uml/playbook2uml-main/playbook2uml/umlstate.py", line 282, in get_entry_point_name
    return self.tasks[0].get_entry_point_name()
IndexError: list index out of range

**Comment by teramako** [comment]
If you want to generate the entire playbook, run without the "-R" option:
```shell
playbook2uml -T playbook playbooks/build_keycloak.yaml
```

If you want to generate only the role part, specify only the role name in the "-R" option and specify the directory where you assume the playbook file is located in the location parameter:
```shell
playbook2uml -T playbook -R keycloak playbooks
```
or
```shell
cd playbooks
playbook2uml -T playbook -R keycloak
```

**Comment by teramako** [comment]
Nevertheless, when an incorrect option is specified, it should stop with an error and usage output.
I will try to fix the parsing code for the command parameters.

**Comment by getvasanth** [comment]
Thanks a lot for the quick reply, I will try and come back.

**Comment by getvasanth** [comment]
Closing it. as I am able to generate the uml.
