### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by getvasanth** [teramako/playbook2uml#7]
Now, it creates only for the main.yaml file in the playbook or roles., any possiblities to include_tasks playbooks as well?

it would be nice to have

**Comment by teramako** [comment]
Do you mean that you also want to output tasks that are read from `include_tasks` in the playbook?

If you use `import_tasks` for static loading, it is possible, but not for `include_tasks`, which is a dynamic loading.

**Comment by getvasanth** [comment]
Sorry @teramako I missed your message, Yes, roles/ROLE_NAME/tasks folder has other tasks, which are called based on condition, can those be included?

**Comment by getvasanth** [comment]
@teramako have moved from include_tasks to import_tasks, it looks good. 

Thanks
Vasanth
